apiVersion: v1
kind: Pod
metadata:
 name: test-qoe-pb
spec:
 nodeName: whx-rn
 containers:
 - image: loyoladesa/test_qoe:1.12
   name: test-container
   volumeMounts:
   - mountPath: /home 
     name: dados-qoe
 volumes:
 - name: dados-qoe
   hostPath:
    path: /data 