apiVersion: v1
kind: Pod
metadata:
 name: test-qoe-go-3
spec:
 nodeName: ids-go
 containers:
 - image: loyoladesa/test_qoe:1.12
   name: test-container
   volumeMounts:
   - mountPath: /home 
     name: dados-qoe-rj
 volumes:
 - name: dados-qoe-rj
   hostPath:
    path: /data 