apiVersion: v1
kind: Pod
metadata:
  name: nginx-server-pod-3
  labels:
   app: nginx-server-pod-3
spec:
  nodeName: ids-rj
  containers:
  - name: nginx-server-3
    image: loyoladesa/server_nginx:1.3
    ports:
    - containerPort: 5215
  - name: ngrok
    image: ngrok/ngrok:latest
    env:
    - name: NGROK_AUTHTOKEN
      value: "2fcZ1KzNGtWXIfMPdcPIqsw6irN_61L8B67QBYThwTYWzFJ5n"
    args:
    - http
    - --domain=qoernp.ngrok.app
    - "5215"