apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: loyoladesa/server_nginx:1.3
        ports:
        - containerPort: 5215
