apiVersion: v1
kind: Service
metadata:
  name: nginx-server-service
spec:
  selector:
    app: nginx-server
  ports:
    - protocol: TCP
      port: 5215
      targetPort: 5215
  type: LoadBalancer # ou NodePort, dependendo de como você quer expor o serviço
